In [1]:
# This is 100 numpy exercises
# http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html
# I have done it until #60

In [2]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config()

1.11.3
blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/tmachida/.pyenv/versions/anaconda3-4.3.1/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/tmachida/.pyenv/versions/anaconda3-4.3.1/include']
blas_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/tmachida/.pyenv/versions/anaconda3-4.3.1/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/tmachida/.pyenv/versions/anaconda3-4.3.1/include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/Users/tmachida/.pyenv/versions/anaconda3-4.3.1/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/tmachida/.pyenv/versions/anaconda3-4.3

In [4]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [5]:
np.info(np.add)

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [7]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [9]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4]),)


In [11]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [12]:
Z = np.random.random((3, 3, 3))
print(Z)

[[[ 0.19400333  0.47391217  0.44539432]
  [ 0.96732968  0.54577055  0.00218553]
  [ 0.21667127  0.50670981  0.58945877]]

 [[ 0.46447054  0.60646052  0.09743569]
  [ 0.58479768  0.52224867  0.14947516]
  [ 0.68795646  0.56962081  0.7313427 ]]

 [[ 0.96759369  0.01531016  0.78729381]
  [ 0.5508132   0.63232093  0.15373495]
  [ 0.87856155  0.37856578  0.97915822]]]


In [13]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(Z, Zmin, Zmax)

[[ 0.67954443  0.07491533  0.2606237   0.85744767  0.66806216  0.80265113
   0.48174325  0.11422355  0.74591235  0.19220193]
 [ 0.81181352  0.26521567  0.45459062  0.56532525  0.59632862  0.13635018
   0.71275956  0.37908997  0.9356725   0.81959061]
 [ 0.24879783  0.77386317  0.12820213  0.4271308   0.2789507   0.71401409
   0.35917513  0.31776611  0.6056528   0.37424192]
 [ 0.46259094  0.60915121  0.16836828  0.76333382  0.49094431  0.73825113
   0.74596334  0.5855794   0.90026329  0.13169705]
 [ 0.48997023  0.64843608  0.82104711  0.30769736  0.94591195  0.067663
   0.16239858  0.10000908  0.0561157   0.52913072]
 [ 0.88630831  0.02946842  0.13630649  0.26397073  0.60133139  0.38162428
   0.72457069  0.14998643  0.11500227  0.49529702]
 [ 0.9533791   0.20018602  0.08945505  0.94177943  0.61877399  0.39214145
   0.87346506  0.05171368  0.79186448  0.71010212]
 [ 0.76303859  0.5335593   0.23245818  0.91709503  0.76571964  0.1393312
   0.3338621   0.02882897  0.88458753  0.34464013]
 [ 

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.508827172966


In [15]:
Z = np.ones((10, 10))
Z[1: -1, 1: -1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [16]:
0 * np.nan

nan

In [17]:
np.nan == np.nan

False

In [18]:
np.inf > np.nan

False

In [19]:
np.nan - np.nan

nan

In [20]:
0.3 == 3 * 0.1

False

In [21]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


In [23]:
Z = np.tile( np.array([[0, 1], [1, 0]]), (4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
Z = np.random.random((5, 5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin) / (Zmax - Zmin)
print(Z)

[[  4.01810793e-01   7.95682499e-01   7.87677179e-01   4.98886142e-01
    4.27726717e-01]
 [  3.77934476e-04   3.43260495e-01   9.18037400e-01   4.84962962e-01
    1.11971122e-01]
 [  8.26361916e-01   5.96571749e-01   9.39752292e-01   7.58424215e-01
    3.66670330e-01]
 [  4.32012513e-01   3.38671228e-02   6.49664555e-01   9.01457347e-01
    1.00000000e+00]
 [  9.14674065e-01   8.99013382e-01   6.31922477e-01   3.21114412e-01
    0.00000000e+00]]


In [25]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(Z)

[[  4.01810793e-01   7.95682499e-01   7.87677179e-01   4.98886142e-01
    4.27726717e-01]
 [  3.77934476e-04   3.43260495e-01   9.18037400e-01   4.84962962e-01
    1.11971122e-01]
 [  8.26361916e-01   5.96571749e-01   9.39752292e-01   7.58424215e-01
    3.66670330e-01]
 [  4.32012513e-01   3.38671228e-02   6.49664555e-01   9.01457347e-01
    1.00000000e+00]
 [  9.14674065e-01   8.99013382e-01   6.31922477e-01   3.21114412e-01
    0.00000000e+00]]


In [26]:
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [27]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [28]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


In [29]:
Z = arange(11)
print(Z ** Z)
print(Z <- Z)
print(1j * Z)
print(Z / 1 / 1)
# print(Z < Z > Z) This is illegal.

[          1           1           4          27         256        3125
       46656      823543    16777216   387420489 10000000000]
[False False False False False False False False False False False]
[ 0. +0.j  0. +1.j  0. +2.j  0. +3.j  0. +4.j  0. +5.j  0. +6.j  0. +7.j
  0. +8.j  0. +9.j  0.+10.j]
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [30]:
print(np.array(0) // np.array(0))
print(np.array(0) // np.array(0.))
print(np.array(0) / np.array(0))
print(np.array(0) / np.array(0.))

0
nan
nan
nan


/Users/tmachida/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  if __name__ == '__main__':
/Users/tmachida/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in floor_divide
  from ipykernel import kernelapp as app
/Users/tmachida/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/ipykernel/__main__.py:3: RuntimeWarning: invalid value encountered in true_divide
  app.launch_new_instance()
/Users/tmachida/.pyenv/versions/anaconda3-4.3.1/lib/python3.6/site-packages/ipykernel/__main__.py:4: RuntimeWarning: invalid value encountered in true_divide


In [31]:
Z = np.random.uniform(0, 10, 10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z.astype(int))
print(np.trunc(Z))

[ 4.  6.  0.  3.  2.  4.  0.  3.  2.  9.]
[ 4.  6.  0.  3.  2.  4.  0.  3.  2.  9.]
[ 4.  6.  0.  3.  2.  4.  0.  3.  2.  9.]
[4 6 0 3 2 4 0 3 2 9]
[ 4.  6.  0.  3.  2.  4.  0.  3.  2.  9.]


In [32]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [33]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [34]:
Z = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(Z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


In [35]:
Z = np.random.random(10)
Z.sort()
print(Z)

[ 0.10834067  0.19962034  0.27015965  0.50771786  0.51602055  0.57556169
  0.71815117  0.72273939  0.73254448  0.96624534]


In [36]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [37]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [38]:
Z = np.zeros(10)
Z.flags.writeable = False
try:
    Z[0] = 1
except:
    print("Z is immutable")

Z is immutable


In [39]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan(Y, X)
print(R)
print(T)

[ 0.94065538  0.9849313   0.66225328  0.24974745  0.83239844  1.13690585
  0.87270145  0.78498494  0.55640773  1.07853664]
[ 0.64284629  0.36783447  0.44513234  0.23509663  0.6698981   0.77785614
  0.66202072  0.4738456   0.43424542  0.71737145]


In [40]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[ 0.          0.02698828  0.42957087  0.66687263  0.10631849  0.69912505
  0.00662195  0.21102049  0.2086704   0.36792763]


In [41]:
Z = np.zeros((10, 10), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 10),
                             np.linspace(0, 1, 10))
print(Z)

[[(0.0, 0.0) (0.1111111111111111, 0.0) (0.2222222222222222, 0.0)
  (0.3333333333333333, 0.0) (0.4444444444444444, 0.0)
  (0.5555555555555556, 0.0) (0.6666666666666666, 0.0)
  (0.7777777777777777, 0.0) (0.8888888888888888, 0.0) (1.0, 0.0)]
 [(0.0, 0.1111111111111111) (0.1111111111111111, 0.1111111111111111)
  (0.2222222222222222, 0.1111111111111111)
  (0.3333333333333333, 0.1111111111111111)
  (0.4444444444444444, 0.1111111111111111)
  (0.5555555555555556, 0.1111111111111111)
  (0.6666666666666666, 0.1111111111111111)
  (0.7777777777777777, 0.1111111111111111)
  (0.8888888888888888, 0.1111111111111111) (1.0, 0.1111111111111111)]
 [(0.0, 0.2222222222222222) (0.1111111111111111, 0.2222222222222222)
  (0.2222222222222222, 0.2222222222222222)
  (0.3333333333333333, 0.2222222222222222)
  (0.4444444444444444, 0.2222222222222222)
  (0.5555555555555556, 0.2222222222222222)
  (0.6666666666666666, 0.2222222222222222)
  (0.7777777777777777, 0.2222222222222222)
  (0.8888888888888888, 0.222222222222

In [42]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.16363712


In [43]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


In [44]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25, 25))
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

In [45]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z - v)).argmin()
print(Z[index])

69


In [46]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                    ('color',   [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))]


In [47]:
Z = np.random.random((10, 2))
X, Y = np.atleast_2d(Z[:, 0]), np.atleast_2d(Z[:, 1])
D = np.sqrt( (X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[ 0.          0.41838321  0.3621783   0.13862197  0.75566397  0.40962044
   0.6056707   0.828215    0.23979617  0.25327584]
 [ 0.41838321  0.          0.17138382  0.29410202  0.63126187  0.74949773
   0.24042385  0.47134146  0.52539595  0.32199002]
 [ 0.3621783   0.17138382  0.          0.28334299  0.49123792  0.61578579
   0.24971712  0.46617671  0.39253592  0.1754212 ]
 [ 0.13862197  0.29410202  0.28334299  0.          0.74026838  0.53546148
   0.50540907  0.73583062  0.33781207  0.24824021]
 [ 0.75566397  0.63126187  0.49123792  0.74026838  0.          0.74714903
   0.48045405  0.4662032   0.61332363  0.50475891]
 [ 0.40962044  0.74949773  0.61578579  0.53546148  0.74714903  0.
   0.85104114  1.02507634  0.22477794  0.44036538]
 [ 0.6056707   0.24042385  0.24971712  0.50540907  0.48045405  0.85104114
   0.          0.23300636  0.63286216  0.4168429 ]
 [ 0.828215    0.47134146  0.46617671  0.73583062  0.4662032   1.02507634
   0.23300636  0.          0.8200473   0.61461839]
 [ 0.239

In [48]:
# much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
Z = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(Z, Z)
print(D)

[[ 0.          0.34549141  0.23363411  0.26117699  0.27788779  0.52085626
   0.61866571  0.54297427  0.0797508   0.48579783]
 [ 0.34549141  0.          0.37813174  0.5967522   0.24137633  0.54538078
   0.2754304   0.40205208  0.4248406   0.82895062]
 [ 0.23363411  0.37813174  0.          0.43300104  0.15961262  0.73789898
   0.63530867  0.70767137  0.26853944  0.60614195]
 [ 0.26117699  0.5967522   0.43300104  0.          0.52828919  0.55797835
   0.86202845  0.6828708   0.18508229  0.23709363]
 [ 0.27788779  0.24137633  0.15961262  0.52828919  0.          0.6988772
   0.4807567   0.61685273  0.34457262  0.73066314]
 [ 0.52085626  0.54538078  0.73789898  0.55797835  0.6988772   0.
   0.66352732  0.25193907  0.53862522  0.75014477]
 [ 0.61866571  0.2754304   0.63530867  0.86202845  0.4807567   0.66352732
   0.          0.43460079  0.69717744  1.09737642]
 [ 0.54297427  0.40205208  0.70767137  0.6828708   0.61685273  0.25193907
   0.43460079  0.          0.59329263  0.9069964 ]
 [ 0.0797

In [49]:
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [50]:
Z = np.genfromtxt("missing.dat", delimiter=",")
print(Z)

[[  1.   2.   3.   4.   5.]
 [  6.  nan  nan   7.   8.]
 [ nan  nan   9.  10.  11.]]


In [51]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [52]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X * X + Y * Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))
print(G)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

In [53]:
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
print(np.put(Z, np.random.choice(range(n*n), p, replace=False),1))

None


In [54]:
# Author: Warren Wecksser
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.32679554 -0.05396667  0.19508227 -0.14347674  0.27269683  0.21780575
  -0.1688673  -0.21634634 -0.01098354  0.23485128]
 [ 0.38310603  0.3420833  -0.44264997 -0.21597458  0.10437427  0.22394482
  -0.5462125  -0.04315526 -0.1540707   0.34855459]
 [ 0.09793923  0.19648321 -0.02400072 -0.29596467  0.01633349 -0.43822521
  -0.29762161  0.5395059   0.42767866 -0.22212828]
 [ 0.20049277  0.22735575 -0.1677381   0.10187674 -0.41124958  0.01598262
  -0.39792148  0.32211067 -0.17885548  0.28794609]
 [-0.41258447  0.34722542 -0.06104722 -0.23337706  0.31200952  0.03933663
  -0.44022921  0.06886847  0.18477239  0.19502553]]
[[-0.32679554 -0.05396667  0.19508227 -0.14347674  0.27269683  0.21780575
  -0.1688673  -0.21634634 -0.01098354  0.23485128]
 [ 0.38310603  0.3420833  -0.44264997 -0.21597458  0.10437427  0.22394482
  -0.5462125  -0.04315526 -0.1540707   0.34855459]
 [ 0.09793923  0.19648321 -0.02400072 -0.29596467  0.01633349 -0.43822521
  -0.29762161  0.5395059   0.42767866 -0.22212828]

In [55]:
# Author: Steve Tjoa

Z = np.random.randint(0, 10, (3,3))
print(Z)
print(Z[Z[:, 1].argsort()])

[[9 9 4]
 [1 3 1]
 [0 5 4]]
[[1 3 1]
 [0 5 4]
 [9 9 4]]


In [56]:
# Author: Warren Wecksser

Z = np.random.randint(0, 3, (3, 10))
print((~Z.any(axis=0)).any())

True


In [57]:
Z = np.random.uniform(0, 1, 10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.346974865045


In [58]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
        
Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


In [59]:
# Author: Brett Olsen

Z = np.ones(10)
print(Z)
I = np.random.randint(0, len(Z), 20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[3 2 2 8 3 5 3 3 1 5 3 2 5 5 2 0 6 5 6 0]
[ 3.  2.  5.  6.  1.  6.  3.  1.  2.  1.]


In [60]:
# Author: Alan G Issac

X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


In [61]:
# Author: Nadav Horesh

w, h = 16, 16
I = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
F = I[..., 0] * 256 * 256 + I[..., 1] * 256 + I[..., 2]
n = len(np.unique(F))
print(n)
print(np.unique(I))

4
[0 1]


In [62]:
A = np.random.randint(0, 10, (3, 4, 3, 4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[48 52 51 62]
 [36 52 41 48]
 [44 40 61 51]]


In [63]:
# Author: Jaime Fernandez del Rio

D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[ 0.46699854  0.51693399  0.34985605  0.4686148   0.61921312  0.45320567
  0.57549694  0.57609036  0.41929885  0.45098165]


In [64]:
# Author: Mathieu Blondel

A = np.random.random(size=(1, 10))
B = np.random.random(size=(10, 1))
# slow version
np.diag(np.dot(A, B))

# fast version
np.sum(A * B.T, axis=1)

# faster version
np.einsum("ij,ji->i", A, B)

array([ 4.01985771])